version: '3.4'

services:
  crawler-api-local-debug:
    env_file:
      - ../.env
    build:
      context: ./
      dockerfile: debug.Dockerfile
      target: debug
    volumes:
      - ..:/workspaces/crawler-api-local
      - ~/.ssh:/root/.ssh-localhost:ro
    ports:
      - '3000:3000'
    container_name: crawler-api-local-debug
    image: local/crawler-api-local-debug:latest
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
